// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type { CompetitionPodiumsData, CompetitionPodiumsErrors, CompetitionPodiumsResponses, LivePodiumsData, LivePodiumsResponses, ResultsByCompetitionData, ResultsByCompetitionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Gets Information about the Podiums of the Live Results
 */
export const livePodiums = <ThrowOnError extends boolean = false>(options: Options<LivePodiumsData, ThrowOnError>): RequestResult<LivePodiumsResponses, unknown, ThrowOnError> => options.client.get<LivePodiumsResponses, unknown, ThrowOnError>({ url: '/v1/competitions/{competitionId}/live/podiums', ...options });

/**
 * Returns the podium results
 */
export const competitionPodiums = <ThrowOnError extends boolean = false>(options: Options<CompetitionPodiumsData, ThrowOnError>): RequestResult<CompetitionPodiumsResponses, CompetitionPodiumsErrors, ThrowOnError> => options.client.get<CompetitionPodiumsResponses, CompetitionPodiumsErrors, ThrowOnError>({ url: '/v0/competitions/{competitionId}/podiums', ...options });

/**
 * Returns all results
 */
export const resultsByCompetition = <ThrowOnError extends boolean = false>(options: Options<ResultsByCompetitionData, ThrowOnError>): RequestResult<ResultsByCompetitionResponses, unknown, ThrowOnError> => options.client.get<ResultsByCompetitionResponses, unknown, ThrowOnError>({ url: '/v0/competitions/{competitionId}/results', ...options });
