// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://www.worldcubeassociation.org/api' | 'http://localhost:3000/api' | (string & {});
};

export type RegistrationDataV2 = {
    id: number;
    registrant_id: number;
    user_id: number;
    guests?: number;
    user: {
        id: number;
        name: string;
        gender: string;
        country_iso2: string;
        wca_id: string | null;
        dob?: string;
        email?: string;
    };
    competing: {
        event_ids: Array<string>;
        registration_status?: string;
        registered_on?: string;
        comment?: string;
        admin_comment?: string;
    };
    payment?: {
        has_paid?: boolean;
        payment_status?: string;
        paid_amount_iso?: number;
        currency_code?: string;
        updated_at?: string;
    };
};

export type BaseRegistrationConfig = {
    key: string;
    isEditable: boolean;
    parameters?: {
        [key: string]: unknown;
    };
};

export type RequirementsStepConfig = BaseRegistrationConfig;

export type WcifAttemptResult = number;

export type WcifQualificationAttemptResult = {
    whenDate: string;
    type: string;
    resultType: 'single' | 'average';
    level: WcifAttemptResult;
};

export type WcifRanking = number;

export type WcifQualificationRanking = {
    whenDate: string;
    type: string;
    resultType: 'single' | 'average';
    level: WcifRanking;
};

export type WcifQualificationAnyResult = {
    whenDate: string;
    type: string;
    resultType: 'single' | 'average';
};

export type WcifQualification = ({
    type: 'attemptResult';
} & WcifQualificationAttemptResult) | ({
    type: 'ranking';
} & WcifQualificationRanking) | ({
    type: 'anyResult';
} & WcifQualificationAnyResult);

export type WcifPersonalBest = {
    eventId: string;
    best: WcifAttemptResult;
    worldRanking: number;
    continentalRanking: number;
    nationalRanking: number;
    type: 'single' | 'average';
};

export type CompetingStepConfig = BaseRegistrationConfig & {
    parameters: {
        events_per_registration_limit?: number;
        allow_registration_edits: boolean;
        guest_entry_status: 'unclear' | 'free' | 'restricted';
        guests_per_registration_limit?: number;
        guests_enabled: boolean;
        'uses_qualification?': boolean;
        allow_registration_without_qualification: boolean;
        force_comment_in_registration: boolean;
        qualification_wcif: {
            [key: string]: WcifQualification;
        };
        event_ids: Array<string>;
        preferredEvents: Array<string>;
        personalRecords: {
            single: Array<WcifPersonalBest>;
            average: Array<WcifPersonalBest>;
        };
    };
};

export type PaymentStepConfig = BaseRegistrationConfig & {
    parameters: {
        stripePublishableKey: string;
        connectedAccountId: string;
    };
};

export type ApprovalStepConfig = BaseRegistrationConfig & {
    parameters: {
        'auto_accept_enabled?': boolean;
        auto_accept_preference?: 'disabled' | 'bulk' | 'live';
    };
};

export type RegistrationConfig = ({
    key: 'requirements';
} & RequirementsStepConfig) | ({
    key: 'competing';
} & CompetingStepConfig) | ({
    key: 'payment';
} & PaymentStepConfig) | ({
    key: 'approval';
} & ApprovalStepConfig);

export type WcifTimeLimit = {
    centiseconds: number;
    cumulativeRoundIds: Array<string>;
};

export type WcifCutoff = {
    numberOfAttempts: number;
    attemptResult: WcifAttemptResult;
};

export type WcifAdvancementConditionRanking = {
    type: string;
    level: WcifRanking;
};

export type WcifPercent = number;

export type WcifAdvancementConditionPercent = {
    type: string;
    level: WcifPercent;
};

export type WcifAdvancementConditionAttemptResult = {
    type: string;
    level: WcifAttemptResult;
};

export type WcifAdvancementCondition = ({
    type: 'ranking';
} & WcifAdvancementConditionRanking) | ({
    type: 'percent';
} & WcifAdvancementConditionPercent) | ({
    type: 'attemptResult';
} & WcifAdvancementConditionAttemptResult);

export type WcifScramble = string;

export type WcifScrambleSet = {
    id: number;
    scrambles: Array<WcifScramble>;
    extraScrambles: Array<WcifScramble>;
};

export type BaseWcifRound = {
    id: string;
    format: '1' | '2' | '3' | 'a' | 'm';
    timeLimit?: WcifTimeLimit;
    cutoff?: WcifCutoff;
    advancementCondition?: WcifAdvancementCondition;
    scrambleSetCount: number;
    scrambleSets: Array<WcifScrambleSet>;
    extensions: Array<unknown>;
};

export type WcifAttempt = {
    result: WcifAttemptResult;
    reconstruction?: string;
};

export type WcifResult = {
    personId: number;
    ranking?: number;
    attempts: Array<WcifAttempt>;
    best: WcifAttemptResult;
    average: WcifAttemptResult;
};

export type WcifRound = BaseWcifRound & {
    results: Array<WcifResult>;
};

export type BaseAdminRound = WcifRound & {
    state: string;
};

export type OpenRound = BaseAdminRound & {
    total_competitors: number;
    competitors_live_results_entered: number;
};

export type LockedRound = BaseAdminRound & {
    total_competitors: number;
};

export type PendingRound = BaseAdminRound;

export type ReadyRound = BaseAdminRound;

export type LiveRoundAdmin = ({
    state: 'open';
} & OpenRound) | ({
    state: 'locked';
} & LockedRound) | ({
    state: 'pending';
} & PendingRound) | ({
    state: 'ready';
} & ReadyRound);

export type LiveAttempt = {
    value: number;
    attempt_number: number;
};

export type BaseLiveResult = {
    registration_id: number;
    best: number;
    average: number;
    single_record_tag: string;
    average_record_tag: string;
    advancing: boolean;
    advancing_questionable: boolean;
    attempts: Array<LiveAttempt>;
    last_attempt_entered_at: string;
};

export type RoundLiveResult = BaseLiveResult & {
    round_wcif_id: string;
    global_pos: number;
    local_pos: number;
    forecast_statistics?: {
        best_possible_average?: number;
        worst_possible_average?: number;
    };
};

export type LiveCompetitor = {
    id: number;
    registrant_id: number;
    user_id: number;
    name: string;
    country_iso2: string;
};

export type LiveRound = BaseWcifRound & {
    results: Array<RoundLiveResult>;
    competitors: Array<LiveCompetitor>;
    round_id: number;
    state_hash: string;
    linked_round_ids?: Array<string>;
};

export type SubmitLiveResult = {
    attempts: Array<LiveAttempt>;
    registration_id: number;
};

export type BatchSubmitLiveResult = {
    results: Array<SubmitLiveResult>;
};

export type General404 = {
    error: string;
    data: {
        model: string;
        id: string;
    };
};

export type Competition404 = General404 & {
    data?: {
        model: 'Competition';
        id: string;
    };
};

export type UserAvatar = {
    url: string;
    thumb_url?: string;
    is_default: boolean;
};

export type WcifRegistration = {
    wcaRegistrationId: number;
    eventIds: Array<string>;
    status: string;
    isCompeting: boolean;
};

export type WcifAssignment = {
    activityId: number;
    stationNumber: number;
    assignmentCode: string;
};

export type WcifPerson = {
    registrantId: number;
    name: string;
    wcaUserId: number;
    countryIso2: string;
    gender: string;
    birthdate?: string;
    email?: string;
    avatar?: UserAvatar;
    roles: Array<'delegate' | 'trainee-delegate' | 'organizer'>;
    registration?: WcifRegistration;
    assignments: Array<WcifAssignment>;
    personalBests: Array<WcifPersonalBest>;
    extensions: Array<unknown>;
};

export type ByPersonLiveResult = BaseLiveResult & {
    round_wcif_id: string;
    global_pos: number;
    local_pos: number;
    event_id: string;
};

export type LivePerson = WcifPerson & {
    results: Array<ByPersonLiveResult>;
};

export type TeamMembership = {
    id: number;
    friendly_id: string;
    leader: boolean;
    senior_member: boolean;
    name?: string;
    wca_id?: string;
    avatar?: UserAvatar;
};

export type Person = {
    id: number;
    name: string;
    gender?: string;
    wca_id?: string | null;
    country_iso2: string;
    delegate_status: string;
    teams: Array<TeamMembership>;
    url: string;
    avatar: UserAvatar;
};

export type Organizer = Person & {
    delegate_status?: string;
    email?: string;
    avatar?: UserAvatar;
};

export type CompetitionInfo = {
    id: string;
    name: string;
    information: string;
    venue: string;
    contact: string;
    registration_open: string;
    registration_close: string;
    use_wca_registration: boolean;
    guests_enabled: boolean;
    announced_at: string;
    base_entry_fee_lowest_denomination: number;
    currency_code: string;
    start_date: string;
    end_date: string;
    enable_donations: boolean;
    competitor_limit: number;
    extra_registration_requirements?: string;
    on_the_spot_registration: boolean;
    refund_policy_percent: number;
    refund_policy_limit_date: string;
    guests_entry_fee_lowest_denomination: number;
    qualification_results: boolean;
    event_restrictions: boolean;
    cancelled_at?: string;
    waiting_list_deadline_date: string;
    event_change_deadline_date: string;
    competitor_can_cancel: string;
    scoretaking_software: 'external' | 'internal' | 'wca_live';
    url: string;
    website: string;
    city: string;
    venue_address: string;
    venue_details?: string;
    latitude_degrees: number;
    longitude_degrees: number;
    country_iso2: string;
    event_ids: Array<string>;
    main_event_id: string;
    number_of_bookmarks: number;
    'uses_qualification?': boolean;
    'registration_full?': boolean;
    'registration_full_and_accepted?': boolean;
    spots_left?: number;
    tab_names: Array<string>;
    delegates: Array<Person>;
    organizers: Array<Organizer>;
};

export type WcifEvent = {
    id: string;
    rounds: Array<WcifRound>;
    competitorLimit?: number;
    qualification?: WcifQualification;
    extensions: Array<unknown>;
};

export type WcifCountryCode = string;

export type WcifActivityCode = string;

export type WcifActivity = {
    id: number;
    name: string;
    activityCode: WcifActivityCode;
    startTime: string;
    endTime: string;
    childActivities: Array<WcifActivity>;
    scrambleSetId?: number;
    extensions: Array<unknown>;
};

export type WcifRoom = {
    id: number;
    name: string;
    color: string;
    activities: Array<WcifActivity>;
    extensions: Array<unknown>;
};

export type WcifVenue = {
    id: number;
    name: string;
    latitudeMicrodegrees: number;
    longitudeMicrodegrees: number;
    countryIso2: WcifCountryCode;
    timezone: string;
    rooms: Array<WcifRoom>;
    extensions: Array<unknown>;
};

export type WcifSchedule = {
    startDate: string;
    numberOfDays: number;
    venues: Array<WcifVenue>;
};

export type Tabs = {
    id: string;
    competition_id: string;
    name: string;
    content: string;
    display_order: number;
};

export type RegistrationData = {
    id: number;
    competition_id: string;
    user_id: number;
    event_ids: Array<string>;
};

export type Result = {
    id: number;
    pos: number;
    best: number;
    average: number;
    name: string;
    country_iso2: string;
    competition_id: string;
    event_id: string;
    round_type_id: string;
    format_id: string;
    wca_id: string;
    attempts: Array<number>;
    best_index: number;
    worst_index: number;
    regional_single_record: string;
    regional_average_record: string;
};

export type PsychSheet = {
    sort_by: string;
    sort_by_second: string;
    sorted_rankings: Array<{
        name: string;
        user_id: number;
        wca_id: string | null;
        country_iso2: string;
        average_best: number;
        average_rank: number;
        single_best: number;
        single_rank: number;
        tied_previous: boolean;
        pos: number;
    }>;
};

export type CompetitionIndex = {
    id: string;
    name: string;
    short_display_name: string;
    start_date: string;
    end_date: string;
    registration_open: string;
    registration_close: string;
    announced_at: string;
    country_iso2: string;
    city: string;
    venue: string;
    latitude_degrees: number;
    longitude_degrees: number;
    event_ids: Array<string>;
    main_event_id: string;
    competitor_limit: number;
    championship_types: Array<string>;
    results_submitted_at?: string;
    results_posted_at?: string;
    report_posted_at?: string;
    report_posted_by_user?: number;
    delegates?: Array<{
        id: number;
        name: string;
        avatar: UserAvatar;
    }>;
};

export type MyCompetition = {
    id: string;
    name: string;
    website: string;
    start_date: string;
    end_date: string;
    registration_open: string;
    url: string;
    city: string;
    country_iso2: string;
    'results_posted?': boolean;
    'report_posted?': boolean;
    'visible?': boolean;
    'confirmed?': boolean;
    'cancelled?': boolean;
    short_display_name: string;
    championships: Array<string>;
    registration_status?: string;
};

export type CompetingStatus = 'pending' | 'accepted' | 'cancelled' | 'rejected' | 'waiting_list';

export type Results = Array<Result>;

export type Scramble = {
    id: number;
    competition_id: string;
    event_id: string;
    round_type_id: string;
    round_id: number;
    group_id: string;
    is_extra: string;
    scramble_num: number;
    scramble: string;
};

export type ExtendedResult = {
    type?: string;
    id: number;
    pos: number;
    person_id: string;
    person_name: string;
    country_id: string;
    competition_country_id: string;
    competition_id: string;
    competition_name: string;
    event_id: string;
    round_type_id: string;
    round_id: string;
    format_id: string;
    attempts: Array<number>;
    best: number;
    average: number;
    regional_single_record: string;
    regional_average_record: string;
    updated_at: string;
    start_date: string;
    value: number;
};

export type Incident = {
    id: string;
    title: string;
    private_description?: string;
    public_summary: string;
    created_at: string;
    updated_at: string;
    resolved_at: string;
    digest_worthy: boolean;
    digest_sent_at?: string;
    url: string;
    tags: Array<{
        name: string;
        id?: number;
        url: string;
        content_html: string;
    }>;
    competitions: Array<{
        id: string;
        name: string;
        comments?: string;
    }>;
};

export type SearchResultCompetition = {
    class: 'competition';
    id: string;
    name: string;
    city?: string;
    country_iso2?: string;
    url: string;
};

export type SearchResultPerson = {
    class: 'person';
    id: string;
    wca_id?: string;
    name: string;
    country_iso2?: string;
    url: string;
    avatar?: UserAvatar;
};

export type SearchResultRegulation = {
    class: 'regulation';
    id: string;
    content_html?: string;
    url: string;
};

export type SearchResultIncident = {
    class: 'incident';
    id: string;
    title: string;
    url: string;
};

export type SearchResult = ({
    class: 'competition';
} & SearchResultCompetition) | ({
    class: 'person';
} & SearchResultPerson) | ({
    class: 'regulation';
} & SearchResultRegulation) | ({
    class: 'incident';
} & SearchResultIncident);

export type Record = {
    type?: string;
    id: number;
    pos: number;
    person_id: string;
    person_name: string;
    country_id: string;
    competition_country_id: string;
    competition_id: string;
    competition_name: string;
    event_id: string;
    round_type_id: string;
    round_id: string;
    format_id: string;
    attempts: Array<number>;
    best: number;
    average: number;
    regional_single_record: string;
    regional_average_record: string;
    updated_at: string;
    start_date: string;
    value: number;
};

export type RecordByEvent = {
    [key: string]: Array<Record>;
};

export type Rank = {
    id: number;
    person_id: string;
    event_id: string;
    best: number;
    world_rank: number;
    continent_rank: number;
    country_rank: number;
};

export type Medals = {
    gold: number;
    silver: number;
    bronze: number;
    total: number;
};

export type Records = {
    national: number;
    continental: number;
    world: number;
    total: number;
};

export type SingleAndAverageRank = {
    average: Rank;
    single: Rank;
};

export type PersonInfo = {
    person: Person;
    previous_persons?: Array<{
        [key: string]: unknown;
    }>;
    ranks_single?: Array<Rank>;
    ranks_average?: Array<Rank>;
    medals: Medals;
    records: Records;
    personal_records: {
        [key: string]: SingleAndAverageRank;
    };
    championship_podiums: {
        world?: Array<{
            [key: string]: unknown;
        }>;
        continental?: Array<{
            [key: string]: unknown;
        }>;
        greater_china?: Array<{
            [key: string]: unknown;
        }>;
        national?: Array<{
            [key: string]: unknown;
        }>;
    };
    competition_count: number;
    total_solves: number;
};

export type Competitions = Array<CompetitionInfo>;

export type UserGroup = {
    id: number;
    name: string;
    group_type: string;
    parent_group_id?: number;
    is_active: boolean;
    is_hidden: boolean;
    metadata_id?: number;
    metadata_type?: string;
    created_at: string;
    updated_at: string;
    lead_user?: Person;
    metadata?: {
        id?: number;
        status?: string;
        created_at?: string;
        updated_at?: string;
        email?: string;
        preferred_contact_mode?: string;
        friendly_id?: string;
    };
};

export type UserRole = {
    id: number;
    start_date: string;
    end_date: string;
    group: UserGroup;
    user: Person;
    metadata: {
        id?: number;
        status?: string;
        created_at?: string;
        updated_at?: string;
        email?: string;
    };
    class?: string;
};

export type CompetitionPermissions = Array<string> | '*';

export type UserPermissions = {
    can_attend_competitions: {
        scope: CompetitionPermissions;
        until?: string;
    };
    can_organize_competitions: {
        scope: CompetitionPermissions;
    };
    can_administer_competitions: {
        scope: CompetitionPermissions;
    };
    can_view_delegate_admin_page: {
        scope: CompetitionPermissions;
    };
    can_view_delegate_report: {
        scope: CompetitionPermissions;
    };
    can_edit_delegate_report: {
        scope: CompetitionPermissions;
    };
    can_create_groups: {
        scope: Array<string>;
    };
    can_read_groups_current: {
        scope: Array<string>;
    };
    can_read_groups_past: {
        scope: Array<string>;
    };
    can_edit_groups: {
        scope: Array<string>;
    };
    can_access_panels: {
        scope: Array<string>;
    };
    can_request_to_edit_others_profile: {
        scope: Array<string> | '*';
    };
};

export type Translation = {
    version: string;
    language: string;
    language_english: string;
    url: string;
};

export type RegulationsTranslations = {
    current: Array<Translation>;
    outdated: Array<Translation>;
};

export type ExportInfo = {
    export_date: string;
    sql_url: string;
    sql_filesize_bytes: number;
    tsv_url: string;
    tsv_filesize_bytes: number;
    readme: string;
    developer_url?: string;
};

export type RegionalOrganization = {
    name: string;
    country_iso2: string;
    website: string;
    logo_url?: string;
};

export type CompetitionRegistrationsV2Data = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/registrations';
};

export type CompetitionRegistrationsV2Responses = {
    /**
     * Successful response
     */
    200: Array<RegistrationDataV2>;
};

export type CompetitionRegistrationsV2Response = CompetitionRegistrationsV2Responses[keyof CompetitionRegistrationsV2Responses];

export type GetRegistrationsAdminData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/registrations/admin';
};

export type GetRegistrationsAdminErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Competition not found
     */
    404: unknown;
};

export type GetRegistrationsAdminResponses = {
    /**
     * All registrations with admin info
     */
    200: Array<RegistrationDataV2>;
};

export type GetRegistrationsAdminResponse = GetRegistrationsAdminResponses[keyof GetRegistrationsAdminResponses];

export type CompetitionRegistrationConfigData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/registration_config';
};

export type CompetitionRegistrationConfigResponses = {
    /**
     * Successful response
     */
    200: Array<RegistrationConfig>;
};

export type CompetitionRegistrationConfigResponse = CompetitionRegistrationConfigResponses[keyof CompetitionRegistrationConfigResponses];

export type LiveAdminData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds';
};

export type LiveAdminResponses = {
    /**
     * Returns Live Admin Information with Rounds
     */
    200: {
        rounds: Array<LiveRoundAdmin>;
    };
};

export type LiveAdminResponse = LiveAdminResponses[keyof LiveAdminResponses];

export type LiveByRoundData = {
    body?: never;
    path: {
        competitionId: string;
        roundId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}';
};

export type LiveByRoundResponses = {
    /**
     * Returns results
     */
    200: LiveRound;
};

export type LiveByRoundResponse = LiveByRoundResponses[keyof LiveByRoundResponses];

export type PatchV1CompetitionsByCompetitionIdLiveRoundsByRoundIdData = {
    body: SubmitLiveResult;
    path: {
        competitionId: string;
        roundId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}';
};

export type PatchV1CompetitionsByCompetitionIdLiveRoundsByRoundIdResponses = {
    /**
     * Result Updated
     */
    200: {
        status?: string;
    };
};

export type PatchV1CompetitionsByCompetitionIdLiveRoundsByRoundIdResponse = PatchV1CompetitionsByCompetitionIdLiveRoundsByRoundIdResponses[keyof PatchV1CompetitionsByCompetitionIdLiveRoundsByRoundIdResponses];

export type PostV1CompetitionsByCompetitionIdLiveRoundsByRoundIdData = {
    body: SubmitLiveResult;
    path: {
        competitionId: string;
        roundId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}';
};

export type PostV1CompetitionsByCompetitionIdLiveRoundsByRoundIdResponses = {
    /**
     * Result Accepted
     */
    202: {
        status?: string;
    };
};

export type PostV1CompetitionsByCompetitionIdLiveRoundsByRoundIdResponse = PostV1CompetitionsByCompetitionIdLiveRoundsByRoundIdResponses[keyof PostV1CompetitionsByCompetitionIdLiveRoundsByRoundIdResponses];

export type PostV1CompetitionsByCompetitionIdLiveRoundsByRoundIdBatchData = {
    body: BatchSubmitLiveResult;
    path: {
        competitionId: string;
        roundId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}/batch';
};

export type PostV1CompetitionsByCompetitionIdLiveRoundsByRoundIdBatchResponses = {
    /**
     * Batch Accepted
     */
    202: {
        status?: string;
    };
};

export type PostV1CompetitionsByCompetitionIdLiveRoundsByRoundIdBatchResponse = PostV1CompetitionsByCompetitionIdLiveRoundsByRoundIdBatchResponses[keyof PostV1CompetitionsByCompetitionIdLiveRoundsByRoundIdBatchResponses];

export type GetNextCompetitorData = {
    body?: never;
    path: {
        competitionId: string;
        roundId: string;
    };
    query: {
        registration_id: number;
    };
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}/next_if_quit';
};

export type GetNextCompetitorResponses = {
    /**
     * Returns the next competitors who would advance if the registration
     */
    200: {
        status: string;
        next_advancing: Array<LiveCompetitor>;
    };
};

export type GetNextCompetitorResponse = GetNextCompetitorResponses[keyof GetNextCompetitorResponses];

export type CanBeAddedToRoundData = {
    body?: never;
    path: {
        competitionId: string;
        roundId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}/addable_competitors';
};

export type CanBeAddedToRoundResponses = {
    /**
     * The eligible competitors and the states of colinked rounds
     */
    200: {
        registrations: Array<RegistrationDataV2>;
        colinked_status: Array<'locked' | 'open' | 'ready' | 'pending'>;
    };
};

export type CanBeAddedToRoundResponse = CanBeAddedToRoundResponses[keyof CanBeAddedToRoundResponses];

export type QuitCompetitorData = {
    body?: {
        advancing_ids?: Array<number>;
    };
    path: {
        competitionId: string;
        roundId: string;
        registrationId: number;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}/{registrationId}';
};

export type QuitCompetitorResponses = {
    /**
     * Returns number of rounds the competitor was marked as quit in
     */
    200: {
        quit: number;
    };
};

export type QuitCompetitorResponse = QuitCompetitorResponses[keyof QuitCompetitorResponses];

export type AddCompetitorData = {
    body?: never;
    path: {
        competitionId: string;
        roundId: string;
        registrationId: number;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}/{registrationId}';
};

export type AddCompetitorResponses = {
    /**
     * Returns the created empty live result
     */
    200: {
        competitor: LiveCompetitor;
    };
};

export type AddCompetitorResponse = AddCompetitorResponses[keyof AddCompetitorResponses];

export type BulkQuitCompetitorsData = {
    body: {
        registration_ids: Array<number>;
        advancing_ids?: Array<number>;
    };
    path: {
        competitionId: string;
        roundId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}/bulk_quit';
};

export type BulkQuitCompetitorsResponses = {
    /**
     * Returns number of competitors that were marked as quit
     */
    200: {
        quit: number;
    };
};

export type BulkQuitCompetitorsResponse = BulkQuitCompetitorsResponses[keyof BulkQuitCompetitorsResponses];

export type ClearRoundData = {
    body?: never;
    path: {
        competitionId: string;
        roundId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}/clear';
};

export type ClearRoundResponses = {
    /**
     * Returns number of results clear
     */
    200: {
        status: string;
        recreated_rows: number;
    };
};

export type ClearRoundResponse = ClearRoundResponses[keyof ClearRoundResponses];

export type CloseRoundData = {
    body?: never;
    path: {
        competitionId: string;
        roundId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}/close';
};

export type CloseRoundResponses = {
    /**
     * Round closed
     */
    200: {
        status: string;
        deleted_count: number;
    };
};

export type CloseRoundResponse = CloseRoundResponses[keyof CloseRoundResponses];

export type OpenRoundData = {
    body?: never;
    path: {
        competitionId: string;
        roundId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}/open';
};

export type OpenRoundErrors = {
    /**
     * Round cannot be opened
     */
    400: {
        status: 'score taking is not finished in the previous round' | 'round already open' | 'regulation 9m3: a round with 7 or fewer competitors must not have subsequent rounds' | 'regulation 9m2: a round with 15 or fewer competitors must have at most one subsequent round' | 'regulation 9m1: a round with 99 or fewer competitors must have at most two subsequent rounds';
    };
    /**
     * Not logged in
     */
    401: {
        error: string;
    };
    /**
     * Organizer privileges required
     */
    403: {
        error: string;
    };
    /**
     * Competition not found
     */
    404: Competition404;
};

export type OpenRoundError = OpenRoundErrors[keyof OpenRoundErrors];

export type OpenRoundResponses = {
    /**
     * Returns number of locked an created results
     */
    200: {
        status: string;
        created_rows: number;
        locked_rows: number;
    };
};

export type OpenRoundResponse = OpenRoundResponses[keyof OpenRoundResponses];

export type ClearCompetitorData = {
    body?: never;
    path: {
        competitionId: string;
        roundId: string;
        registrationId: number;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/rounds/{roundId}/{registrationId}/clear';
};

export type ClearCompetitorResponses = {
    /**
     * Returns the number of attempts that were deleted
     */
    200: {
        deleted_attempts: number;
    };
};

export type ClearCompetitorResponse = ClearCompetitorResponses[keyof ClearCompetitorResponses];

export type LivePodiumsData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/podiums';
};

export type LivePodiumsResponses = {
    /**
     * Returns podiums with round information
     */
    200: Array<LiveRound>;
};

export type LivePodiumsResponse = LivePodiumsResponses[keyof LivePodiumsResponses];

export type LiveByPersonData = {
    body?: never;
    path: {
        competitionId: string;
        registrationId: string;
    };
    query?: never;
    url: '/v1/competitions/{competitionId}/live/registrations/{registrationId}';
};

export type LiveByPersonResponses = {
    /**
     * Returns a person and their results
     */
    200: LivePerson;
};

export type LiveByPersonResponse = LiveByPersonResponses[keyof LiveByPersonResponses];

export type CompetitionByIdData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v0/competitions/{competitionId}/';
};

export type CompetitionByIdErrors = {
    /**
     * Competition not found
     */
    404: Competition404;
};

export type CompetitionByIdError = CompetitionByIdErrors[keyof CompetitionByIdErrors];

export type CompetitionByIdResponses = {
    /**
     * Successful response
     */
    200: CompetitionInfo;
};

export type CompetitionByIdResponse = CompetitionByIdResponses[keyof CompetitionByIdResponses];

export type CompetitionEventsData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v0/competitions/{competitionId}/events';
};

export type CompetitionEventsErrors = {
    /**
     * Competition not found
     */
    404: Competition404;
};

export type CompetitionEventsError = CompetitionEventsErrors[keyof CompetitionEventsErrors];

export type CompetitionEventsResponses = {
    /**
     * Successful response
     */
    200: Array<WcifEvent>;
};

export type CompetitionEventsResponse = CompetitionEventsResponses[keyof CompetitionEventsResponses];

export type CompetitionScheduleData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v0/competitions/{competitionId}/schedule';
};

export type CompetitionScheduleErrors = {
    /**
     * Competition not found
     */
    404: Competition404;
};

export type CompetitionScheduleError = CompetitionScheduleErrors[keyof CompetitionScheduleErrors];

export type CompetitionScheduleResponses = {
    /**
     * Successful response
     */
    200: WcifSchedule;
};

export type CompetitionScheduleResponse = CompetitionScheduleResponses[keyof CompetitionScheduleResponses];

export type CompetitionTabsData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v0/competitions/{competitionId}/tabs';
};

export type CompetitionTabsErrors = {
    /**
     * Competition not found
     */
    404: Competition404;
};

export type CompetitionTabsError = CompetitionTabsErrors[keyof CompetitionTabsErrors];

export type CompetitionTabsResponses = {
    /**
     * Successful response
     */
    200: Array<Tabs>;
};

export type CompetitionTabsResponse = CompetitionTabsResponses[keyof CompetitionTabsResponses];

export type CompetitionRegistrationsData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v0/competitions/{competitionId}/registrations';
};

export type CompetitionRegistrationsErrors = {
    /**
     * Competition not found
     */
    404: Competition404;
};

export type CompetitionRegistrationsError = CompetitionRegistrationsErrors[keyof CompetitionRegistrationsErrors];

export type CompetitionRegistrationsResponses = {
    /**
     * Successful response
     */
    200: Array<RegistrationData>;
};

export type CompetitionRegistrationsResponse = CompetitionRegistrationsResponses[keyof CompetitionRegistrationsResponses];

export type CompetitionPodiumsData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v0/competitions/{competitionId}/podiums';
};

export type CompetitionPodiumsErrors = {
    /**
     * Competition not found
     */
    404: Competition404;
};

export type CompetitionPodiumsError = CompetitionPodiumsErrors[keyof CompetitionPodiumsErrors];

export type CompetitionPodiumsResponses = {
    /**
     * Successful Response
     */
    200: Array<Result>;
};

export type CompetitionPodiumsResponse = CompetitionPodiumsResponses[keyof CompetitionPodiumsResponses];

export type GetV0CompetitionsByCompetitionIdPsychSheetByEventIdData = {
    body?: never;
    path: {
        competitionId: string;
        eventId: string;
    };
    query?: {
        sort_by?: string;
    };
    url: '/v0/competitions/{competitionId}/psych-sheet/{eventId}';
};

export type GetV0CompetitionsByCompetitionIdPsychSheetByEventIdResponses = {
    /**
     * Successful response
     */
    200: PsychSheet;
};

export type GetV0CompetitionsByCompetitionIdPsychSheetByEventIdResponse = GetV0CompetitionsByCompetitionIdPsychSheetByEventIdResponses[keyof GetV0CompetitionsByCompetitionIdPsychSheetByEventIdResponses];

export type CompetitionListData = {
    body?: never;
    path?: never;
    query?: {
        include_cancelled?: boolean;
        continent?: string;
        country_iso2?: string;
        delegate?: string;
        'event_ids[]'?: Array<string>;
        start?: string;
        end?: string;
        admin_status?: string;
        q?: string;
        sort?: string;
        ongoing_and_future?: string;
    };
    url: '/v0/competition_index';
};

export type CompetitionListResponses = {
    /**
     * Successful response
     */
    200: Array<CompetitionIndex>;
};

export type CompetitionListResponse = CompetitionListResponses[keyof CompetitionListResponses];

export type CompetitionList2Data = {
    body?: never;
    path?: never;
    query?: {
        include_cancelled?: boolean;
        continent?: string;
        country_iso2?: string;
        delegate?: string;
        'event_ids[]'?: Array<string>;
        start?: string;
        end?: string;
        admin_status?: string;
        /**
         * Return competitions the authenticated user can manage. Requires manage_competitions scope.
         */
        managed_by_me?: boolean;
        q?: string;
        sort?: string;
        ongoing_and_future?: string;
    };
    url: '/v0/competitions';
};

export type CompetitionList2Responses = {
    /**
     * Successful response
     */
    200: Array<CompetitionIndex>;
};

export type CompetitionList2Response = CompetitionList2Responses[keyof CompetitionList2Responses];

export type GetMyCompetitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/competitions/mine';
};

export type GetMyCompetitionsResponses = {
    /**
     * Successful response
     */
    200: {
        past_competitions: Array<MyCompetition>;
        future_competitions: Array<MyCompetition>;
        bookmarked_competitions: Array<MyCompetition>;
        registrations_by_competition: {
            [key: string]: CompetingStatus;
        };
    };
};

export type GetMyCompetitionsResponse = GetMyCompetitionsResponses[keyof GetMyCompetitionsResponses];

export type ResultsByCompetitionData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v0/competitions/{competitionId}/results';
};

export type ResultsByCompetitionResponses = {
    /**
     * Successful Response
     */
    200: Results;
};

export type ResultsByCompetitionResponse = ResultsByCompetitionResponses[keyof ResultsByCompetitionResponses];

export type GetScramblesData = {
    body?: never;
    path: {
        competitionId: string;
    };
    query?: never;
    url: '/v0/competitions/{competitionId}/scrambles';
};

export type GetScramblesErrors = {
    /**
     * Competition not found
     */
    404: Competition404;
};

export type GetScramblesError = GetScramblesErrors[keyof GetScramblesErrors];

export type GetScramblesResponses = {
    /**
     * Successful Response
     */
    200: Array<Scramble>;
};

export type GetScramblesResponse = GetScramblesResponses[keyof GetScramblesResponses];

export type GetRankingsData = {
    body?: never;
    path: {
        type: string;
        event_id: string;
    };
    query?: {
        region?: string;
        show?: string;
        gender?: string;
    };
    url: '/v0/results/rankings/{event_id}/{type}';
};

export type GetRankingsResponses = {
    /**
     * Successfully retrieved rankings
     */
    200: {
        rankings: Array<ExtendedResult>;
        timestamp: string;
    };
};

export type GetRankingsResponse = GetRankingsResponses[keyof GetRankingsResponses];

export type RegulationsListData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        tags?: string;
        page?: number;
        per_page?: number;
    };
    url: '/v0/incidents';
};

export type RegulationsListResponses = {
    /**
     * Successful response
     */
    200: Array<Incident>;
};

export type RegulationsListResponse = RegulationsListResponses[keyof RegulationsListResponses];

export type OmniSearchData = {
    body?: never;
    path?: never;
    query: {
        q: string;
    };
    url: '/v0/search';
};

export type OmniSearchResponses = {
    /**
     * Successful response
     */
    200: {
        result: Array<SearchResult>;
    };
};

export type OmniSearchResponse = OmniSearchResponses[keyof OmniSearchResponses];

export type GetRecordsData = {
    body?: never;
    path?: never;
    query?: {
        event_id?: string;
        region?: string;
        show?: string;
        gender?: string;
    };
    url: '/v0/results/records';
};

export type GetRecordsResponses = {
    /**
     * Successfully retrieved records
     */
    200: {
        records: RecordByEvent;
        timestamp: string;
    };
};

export type GetRecordsResponse = GetRecordsResponses[keyof GetRecordsResponses];

export type PersonByWcaIdData = {
    body?: never;
    path: {
        wca_id: string;
    };
    query?: never;
    url: '/v0/persons/{wca_id}/';
};

export type PersonByWcaIdResponses = {
    /**
     * Successful response
     */
    200: PersonInfo;
};

export type PersonByWcaIdResponse = PersonByWcaIdResponses[keyof PersonByWcaIdResponses];

export type PersonResultsData = {
    body?: never;
    path: {
        wca_id: string;
    };
    query?: {
        event_id?: string;
    };
    url: '/v0/persons/{wca_id}/results';
};

export type PersonResultsResponses = {
    /**
     * Successful response
     */
    200: Results;
};

export type PersonResultsResponse = PersonResultsResponses[keyof PersonResultsResponses];

export type PersonRecordsData = {
    body?: never;
    path: {
        wca_id: string;
    };
    query?: never;
    url: '/v0/persons/{wca_id}/records';
};

export type PersonRecordsResponses = {
    /**
     * Successful response
     */
    200: Results;
};

export type PersonRecordsResponse = PersonRecordsResponses[keyof PersonRecordsResponses];

export type PersonCompetitionsData = {
    body?: never;
    path: {
        wca_id: string;
    };
    query?: never;
    url: '/v0/persons/{wca_id}/competitions';
};

export type PersonCompetitionsResponses = {
    /**
     * Successful response
     */
    200: Competitions;
};

export type PersonCompetitionsResponse = PersonCompetitionsResponses[keyof PersonCompetitionsResponses];

export type UserGroupsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by whether the group is active
         */
        isActive?: boolean;
        /**
         * Filter by whether the group is hidden
         */
        isHidden?: boolean;
        /**
         * Filter by group type (e.g., "officers")
         */
        groupType?: string;
        /**
         * Sort by a specific field (e.g., "start_date", "-created_at")
         */
        sort?: string;
    };
    url: '/v0/user_groups';
};

export type UserGroupsResponses = {
    /**
     * A list of user groups
     */
    200: Array<UserGroup>;
};

export type UserGroupsResponse = UserGroupsResponses[keyof UserGroupsResponses];

export type UserRolesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by whether the group is active
         */
        isActive?: boolean;
        /**
         * Filter by whether the group is hidden
         */
        isGroupHidden?: boolean;
        /**
         * Filter by user ID
         */
        userId?: number;
        /**
         * Filter by group ID
         */
        groupId?: number;
        /**
         * Filter by metadata status (e.g., "chair")
         */
        status?: string;
        /**
         * Filter by group type (e.g., "officers")
         */
        groupType?: string;
        /**
         * Filter by parent Group
         */
        parentGroupId?: number;
        /**
         * Filter by whether the user is the lead of the group
         */
        isLead?: boolean;
        /**
         * Sort by a specific field (e.g., "start_date", "-created_at")
         */
        sort?: string;
        /**
         * Number of results per page
         */
        perPage?: number;
    };
    url: '/v0/user_roles';
};

export type UserRolesResponses = {
    /**
     * A list of user roles
     */
    200: Array<UserRole>;
};

export type UserRolesResponse = UserRolesResponses[keyof UserRolesResponses];

export type UserPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/users/me/permissions';
};

export type UserPermissionsResponses = {
    /**
     * Successfully retrieved permissions
     */
    200: UserPermissions;
};

export type UserPermissionsResponse = UserPermissionsResponses[keyof UserPermissionsResponses];

export type RegulationTranslationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/regulations/translations';
};

export type RegulationTranslationsResponses = {
    /**
     * Successful response
     */
    200: RegulationsTranslations;
};

export type RegulationTranslationsResponse = RegulationTranslationsResponses[keyof RegulationTranslationsResponses];

export type PublicExportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/export/public';
};

export type PublicExportsResponses = {
    /**
     * Successfully retrieved exports
     */
    200: ExportInfo;
};

export type PublicExportsResponse = PublicExportsResponses[keyof PublicExportsResponses];

export type KnownTimezonesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/known-timezones';
};

export type KnownTimezonesResponses = {
    /**
     * Successful response
     */
    200: Array<string>;
};

export type KnownTimezonesResponse = KnownTimezonesResponses[keyof KnownTimezonesResponses];

export type RegionalOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/regional-organizations';
};

export type RegionalOrganizationsResponses = {
    /**
     * Retrieved organizations
     */
    200: Array<RegionalOrganization>;
};

export type RegionalOrganizationsResponse = RegionalOrganizationsResponses[keyof RegionalOrganizationsResponses];
